### ISSUE TITLE
Formulas processing.

### ISSUE THREAD

**Issue by zekefast** [gorn/rspreadsheet#5]
I have not find any examples of work with formulas in spreadsheet. Is it possible to do with that library at all?

If not it would be a good extension to it ;)

**Comment by gorn** [comment]
I have added this functionality few days ago and it is in very untested state. Feel free to test it and let me know any observations. However it is really experimental. Every cell object has a formula setter and getter, where you can set formula (starting with =) as string.

**Comment by zekefast** [comment]
@gorn Thanks. Is that in `master`? Have you released this in some numbered version?

**Comment by zekefast** [comment]
@gorn, I found that it is in the `master` know, but not in the `v0.2.7`. Thank you! I am going to check it! I'll write you back!

**Comment by zekefast** [comment]
@gorn, For my purpose of generating formulas in the document it works like a charm! 
I am wondering how circumstances coincidence: you have added it right few days before I need it.
That is really awesome!
Thank you a lot!

**Comment by gorn** [comment]
Yes it is nice coincidence, on the other hand it is motivating, when I see other people use it as well. :) I have relased 0.2.8 with formulas and I will be releasing 0.2.9 soon, because i just found that there is an issue when rewriteing formula by fixed  string. That will be solved, but there is naother mysterious thing in LibreOffice itself - it appears, that each cell has a type, which can be number, string or some other options, but there is not "formula" type and I am not really sure how these two things work together - how one can "guess" from formula what type of value is the result. I was unable to find any docs on this.

**Comment by gorn** [comment]
Formula supporst works from me fine, so this issue is closed. Feel free to open one if you spot any unexpected behaviour.

**Comment by zekefast** [comment]
@gorn Thank you a lot! :muscle:
